import time
import RPi.GPIO as GPIO

# Suppress warnings
GPIO.setwarnings(False)

# Use "GPIO" pin numbering
GPIO.setmode(GPIO.BCM)

GPIO.setup(1, GPIO.IN)
GPIO.setup(2, GPIO.IN)
GPIO.setup(3, GPIO.IN)
GPIO.setup(4, GPIO.IN)
GPIO.setup(5, GPIO.IN)
GPIO.setup(6, GPIO.IN)
GPIO.setup(7, GPIO.IN)
GPIO.setup(8, GPIO.IN)
GPIO.setup(9, GPIO.IN)
GPIO.setup(10, GPIO.IN)
GPIO.setup(11, GPIO.IN)
GPIO.setup(12, GPIO.IN)
GPIO.setup(13, GPIO.IN)
GPIO.setup(14, GPIO.IN)
GPIO.setup(15, GPIO.IN)
GPIO.setup(16, GPIO.IN)
GPIO.setup(17, GPIO.IN)
GPIO.setup(18, GPIO.IN)
GPIO.setup(19, GPIO.IN)
GPIO.setup(20, GPIO.IN)
GPIO.setup(21, GPIO.IN)
GPIO.setup(22, GPIO.IN)
GPIO.setup(23, GPIO.IN)
GPIO.setup(24, GPIO.IN)
GPIO.setup(25, GPIO.IN)
GPIO.setup(26, GPIO.IN)
GPIO.setup(27, GPIO.IN)

# Blink forever
while True:
    print(GPIO.input(1))
    print(GPIO.input(2))
    print(GPIO.input(3))
    print(GPIO.input(4))
    print(GPIO.input(5))
    print(GPIO.input(6))
    print(GPIO.input(7))
    print(GPIO.input(8))
    print(GPIO.input(9))
    print(GPIO.input(10))
    print(GPIO.input(11))
    print(GPIO.input(12))
    print(GPIO.input(13))
    print(GPIO.input(14))
    print(GPIO.input(15))
    print(GPIO.input(16))
    print(GPIO.input(17))
    print(GPIO.input(18))
    print(GPIO.input(19))
    print(GPIO.input(20))
    print(GPIO.input(21))
    print(GPIO.input(22))
    print(GPIO.input(23))
    print(GPIO.input(24))
    print(GPIO.input(25))
    print(GPIO.input(26))
    print(GPIO.input(27))
    time.sleep(1)
